### ISSUE TITLE
Link to gh-pages

### ISSUE THREAD

**Issue by mattagape** [UCL-ARC/hpc-shell#2]
Under 

About - Materials to teach terminal fundamentals for HPC users

on the top right of the repo home page, add the correct link to our gh-pages.

**Comment by dpshelio** [comment]
You'll need to be more specific, about-materials where exactly? on the rendered lesson, on the github settings? Please, add a link to the page you mean.
PS. if it's on the repo, you should have permissions to edit it.

**Comment by mattagape** [comment]
It's http://rits.github-pages.ucl.ac.uk/hpc-shell/

Fixed.
